name: "\U0001F41E Bug report"
description: Report an bug you found in nato-phonetic-alphabet
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: If you intend to submit a PR that fixes this bug, please tell us. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A link to a repository that reproduces the issue. If none is provided it pushes the burden of creating a reproduction project onto the maintainers, which will make it take a longer time for the bug to get resolved.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Please include any console logs around the time this bug occurred. Please try not to take a screenshot but copy paste the log text."
      render: shell
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - annoyance.
        - serious, but I can work around it.
        - blocking all usage of `nato-phonetic-alphabet`.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Add any other context or screenshots about the bug here.
