name: "\U0001F41E Bug report"
description: Report an bug you found in nato-phonetic-alphabet
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Plenty of issues are to be expected since `nato-phonetic-alphabet` has not yet reached version `1.0`.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: If you intend to submit a PR that fixes this bug, please tell us. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A link to a repository that reproduces the issue. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto the maintainers, who as of this moment do not yet receive enough funding to work on nato-phonetic-alphabet fulltime. If no reproduction is provided within a reasonable time-frame, the issue will be closed.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Please include any console logs around the time this bug occurred. Please try not to take a screenshot but copy paste the log text."
      render: shell
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --binaries --browsers --npmPackages "{nato-phonetic-alphabet/*}"`
      render: shell
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - annoyance.
        - serious, but I can work around it.
        - blocking all usage of `nato-phonetic-alphabet`.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Add any other context or screenshots about the bug here.
