name: "Feature Request"
description: Suggest a new element, feature or idea for `nato-phonetic-alphabet`
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request this feature! If your feature request is complex or substantial enough to warrant in-depth discussion, consider discussing it with the maintainers [on discord](https://github.com/sveltejs/rfcs) first.
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: Please provide a clear and concise description of the problem this feature would solve. The more information you can provide here, the better.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the proposed solution
      description: Please provide a clear and concise description of what you would like to happen.
      placeholder: I would like to see...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "Please provide a clear and concise description of any alternative solutions or features you've considered."
  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - nice to have.
        - would make my life easier.
        - i cannot use nato-phonetic-alphabet without it.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Add any other context or screenshots about the feature request here.
