name: "Feature Request"
description: Suggest a dictionary, format or feature for `nato-phonetic-alphabet`
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request this feature!
  - type: textarea
    id: feature
    attributes:
      label: Describe the proposed feature
      description: Please provide a clear and concise description of what you would like.
      placeholder: I would like to see...
    validations:
      required: true
  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - nice to have.
        - would make my life easier.
        - i cannot use `nato-phonetic-alphabet` without it.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Add any other context or screenshots about the feature request here.
