# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ main ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.3
          run_install: true
      - run: pnpm test
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
      - run: pnpm build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

#   publish-gpr:
#     needs: publish-npm
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 16
#           registry-url: https://npm.pkg.github.com/
#       - name: Cache pnpm modules
#         uses: actions/cache@v2
#         with:
#           path: ~/.pnpm-store
#           key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
#           restore-keys: |
#             ${{ runner.os }}-
#       - uses: pnpm/action-setup@v2.0.1
#         with:
#           version: 6.23.3
#           run_install: true
#       - run: pnpm build
#       - run: npm publish --access public
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
